### ISSUE TITLE
[Feature] Ability to show integrated address and/or copy it to clipboard

### ISSUE THREAD

**Issue by moneroexamples** [amiuhle/kasisto#29]
I'm using your project. Very good. But it would be great if there was an ablility to copy the integrated address, so that I can copy and paste it into, for example, command line wallet, gui wallet, open monero wallet, send by email, post in chat, etc. Having QR code only is very limiting.

**Comment by amiuhle** [comment]
> I'm using your project. Very good.
:+1: 

Yes, that's planned, probably by clicking on the barcode and then it will kind of flip and show the integrated address, with an option to copy to clipboard.

I don't want to display it permanently because there's not really a use for it in production.
