### ISSUE TITLE
[feature] v7 testnet support

### ISSUE THREAD

**Issue by moneroexamples** [amiuhle/kasisto#34]
Do you have demo running on v7 testnet? I think current demo https://amiuhle.github.io/kasisto/#/ is for v6 testnet only?

**Comment by amiuhle** [comment]
Yes, that's for v6 testnet only, because I expect people to use a mobile wallet to test, which are running release binaries and therefore use the v6 testnet.

You can set up your own v7 testnet version: https://github.com/amiuhle/kasisto/blob/master/docs/server-setup.md

**Comment by moneroexamples** [comment]
Thanks, I will try to setup it for myself.
